#spring.jpa.hibernate.ddl-auto=update
#
#spring.datasource.url=jdbc:postgresql://localhost:3306/springdb
#spring.datasource.username=postgres
#spring.datasource.password=123456
#spring.jpa.hibernate.ddl-auto
#
#spring.jpa.show-sql=true
#

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/profileDB?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true

server:
  port: 9191
  servlet:
    session:
      cookie:
        name: pCookie
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: mobile
      user-authorization-uri: http://localhost:8181/oauth/authorize
      access-token-uri: http://localhost:8181/oauth/token
    resource:
      token-info-uri: http://localhost:8181/oauth/check_token