spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saathi?createIfNotExist=true
    username: root
    password: 123456

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true

 


