spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/saathi
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: profile

